apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhtap-integ
  janus-idp.io/tekton: rhtap-integ
  backstage.io/kubernetes-id: rhtap-integ
  backstage.io/kubernetes-namespace: rhtap-integ 
  app.kubernetes.io/part-of: rhtap-integ
resources: 
- deployment.yaml
- route.yaml
- service.yaml
