apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-integ
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-integ 
  name: rhtap-integ
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhtap-integ
    weight: 100 
